# Ultimate NumPy Cheat Sheet & Visual Guide
> An exhaustive, visual, and zero-fluff reference manual for NumPy fundamentals, operations, and linear algebra.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/AdhamAmgadElSharkawy/numpy-visual-guide/blob/main/learnnumpy.ipynb)
![Python](https://img.shields.io/badge/Python-3.10%2B-blue)
![NumPy](https://img.shields.io/badge/NumPy-2.0%2B-green)
![License](https://img.shields.io/badge/License-MIT-yellow)
---

### Table of Contents
1. [NumPy Basics & Array Creation](#1-numpy-basics--array-creation)
2. [Built-in Array Initializers & Data Types](#2-built-in-array-initializers--data-types)
3. [Indexing & Slicing](#3-indexing--slicing)
4. [Memory: Views vs. Deep Copies](#4-memory-views-vs-deep-copies)
5. [Reshaping, Transposing & Stacking](#5-reshaping-transposing--stacking)
6. [Arithmetic & Vectorized Operations](#6-arithmetic--vectorized-operations)
7. [Broadcasting Rules](#7-broadcasting-rules)
8. [Aggregate & Statistical Functions](#8-aggregate--statistical-functions)
9. [Handling Missing Data (NaNs & Infs)](#9-handling-missing-data-nans--infs)
10. [Filtering & Boolean Indexing](#10-filtering--boolean-indexing)
11. [Sorting & Unique Values](#11-sorting--unique-values)
12. [Random Numbers & Distributions (np.random)](#12-random-numbers--distributions-nprandom)
13. [Linear Algebra (np.linalg)](#13-linear-algebra-nplinalg)
14. [Saving & Loading Arrays (File I/O)](#14-saving--loading-arrays-file-io)

## Quick Start
Open directly in your browser:
**[Launch in Google Colab](https://colab.research.google.com/github/AdhamAmgadElSharkawy/numpy-visual-guide/blob/main/learnnumpy.ipynb)**

---
⭐ **If you find this reference useful, don't forget to give it a star!**

# 1. NumPy Basics & Array Creation
```text
Understanding Array Dimensions & Axes:

     1D Array (Vector)                      2D Array (Matrix)
      shape: (4,)                            shape: (2, 3)
                                              Axis 1 (Columns ──>)
        Axis 0                             ┌───────────────────────┐
    [ 1,  2,  3,  4 ]             Axis 0   │  [ 1 ,  2 ,  3 ],     │
                                 (Rows │)  │  [ 4 ,  5 ,  6 ]      │
                                       ▼   └───────────────────────┘
```

In [99]:
import numpy as np

# 1. Lists duplicate/replicate elements; NumPy arrays perform element-wise arithmetic
my_list = [1, 2, 3, 4]
print("List * 2 (repeats elements):", my_list * 2)  # [1, 2, 3, 4, 1, 2, 3, 4]

array = np.array([1, 2, 3, 4])
print("Array * 2 (vectorized math):", array * 2)    # [2, 4, 6, 8]
print("Type:", type(array))                         # <class 'numpy.ndarray'>

# 2. Essential Array Attributes:
# - .ndim : Number of dimensions/axes (1 = 1D vector, 2 = 2D matrix)
# - .shape: Tuple of integers indicating the size along each axis
print("Dimensions (.ndim):", array.ndim)
print("Shape (.shape):", array.shape)

List * 2 (repeats elements): [1, 2, 3, 4, 1, 2, 3, 4]
Array * 2 (vectorized math): [2 4 6 8]
Type: <class 'numpy.ndarray'>
Dimensions (.ndim): 1
Shape (.shape): (4,)


# 2. Built-in Array Initializers & Data Types
```text
np.arange vs. np.linspace:

  np.arange(0, 10, step=2)  ──> Focuses on STEP SIZE (Jump by 2)
  [ 0 ] ──(+2)──> [ 2 ] ──(+2)──> [ 4 ] ──(+2)──> [ 6 ] ──(+2)──> [ 8 ]

  np.linspace(0, 1, num=5)  ──> Focuses on NUMBER OF SAMPLES (Divides range evenly)
  [ 0.00 ] ────── [ 0.25 ] ────── [ 0.50 ] ────── [ 0.75 ] ────── [ 1.00 ]
```

In [100]:
# Intrinsic initializers
zeros = np.zeros((2, 3))                          # 2x3 matrix of float zeros
ones = np.ones((3, 3), dtype=np.int32)            # 3x3 matrix with explicit int32 dtype
full = np.full((2, 2), 7)                         # 2x2 matrix filled with 7
identity = np.eye(3)                              # 3x3 Identity matrix

# Numerical ranges
grid_step = np.arange(0, 10, 2)                   # [0, 2, 4, 6, 8] (defined step)
grid_linear = np.linspace(0, 1, 5)                # 5 evenly spaced points between 0 and 1

# Type casting (.astype)
float_arr = np.array([1.2, 2.7, 3.9])
int_arr = float_arr.astype(int)                   # Casts to [1, 2, 3]

print("Zeros:\n", zeros)
print("Arange:", grid_step)
print("Linspace:", grid_linear)
print("Casted Ints:", int_arr, "| Dtype:", int_arr.dtype)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Casted Ints: [1 2 3] | Dtype: int64


# 3. Indexing & Slicing

```text
2D Slicing: array[row_start:row_end , col_start:col_end]

              Col 0      Col 1      Col 2      Col 3
           ┌──────────┬──────────┬──────────┬──────────┐
  Row 0    │    1     │    2     │    3     │    4     │
           ├──────────┼──────────┼──────────┼──────────┤
  Row 1    │    5     │  ★ [6]   │  ★ [7]   │    8     │  ──> array[1:3, 1:3]
           ├──────────┼──────────┼──────────┼──────────┤
  Row 2    │    9     │  ★ [10]  │  ★ [11]  │   12     │
           ├──────────┼──────────┼──────────┼──────────┤
  Row 3    │   13     │   14     │   15     │   16     │
           └──────────┴──────────┴──────────┴──────────┘
```

<p align="center">
  <img src="assets/3d_slicing.gif" width="480" alt="3D NumPy Slicing Animation">
  <br>
  <em>Visualizing 3D Tensor Slicing: Extracting a (2, 2, 2) sub-array from a (3, 3, 3) tensor.</em>
</p>

In [101]:
# Syntax: array[start:end:step]
array = np.array([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9,  10, 11, 12],
                  [13, 14, 15, 16]])

# Row Slicing
print("Rows 0 to 2:\n", array[0:3])
print("Every 2nd row (step=2):\n", array[0:4:2])

# 2D Slicing: array[row_slice, col_slice]
print("First column (all rows):", array[:, 0])
print("First 3 columns:\n", array[:, 0:3])
print("Columns 0 and 2 (step=2):\n", array[:, ::2])
print("Top-left 2x2 matrix:\n", array[0:2, 0:2])
print("Reverse rows:\n", array[::-1, :])

Rows 0 to 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Every 2nd row (step=2):
 [[ 1  2  3  4]
 [ 9 10 11 12]]
First column (all rows): [ 1  5  9 13]
First 3 columns:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Columns 0 and 2 (step=2):
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Top-left 2x2 matrix:
 [[1 2]
 [5 6]]
Reverse rows:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


# 4. Memory: Views vs. Deep Copies

```text
Memory Allocation:
  Original Array ───> [ 10, 20, 30, 40 ] (Buffer in Memory)
                            ▲
  Slice (View)  ────────────┘ (Points to SAME memory -> Mutates Original)

  .copy() Array ────> [ 10, 20 ] (Independent NEW memory buffer)
```

In [102]:
# Slicing creates a VIEW: Modifying the slice alters the original array!
original = np.array([10, 20, 30, 40])
view_arr = original[0:2]
view_arr[0] = 999
print("Original mutated via view:", original)      # [999, 20, 30, 40]

# Use .copy() to create an independent array in memory
safe_copy = original[0:2].copy()
safe_copy[0] = 0
print("Safe Copy:", safe_copy)
print("Original untouched:", original)

Original mutated via view: [999  20  30  40]
Safe Copy: [ 0 20]
Original untouched: [999  20  30  40]


# 5. Reshaping, Transposing & Stacking

```text
Stacking Operations:
       np.vstack((a, b))               np.hstack((a, b))
        ┌────┬────┐                     ┌────┬────┬────┬────┐
   a -> │ 1  │ 2  │                a -> │ 1  │ 2  │ 5  │ 6  │ <- b
        ├────┼────┤                     ├────┼────┼────┼────┤
        │ 3  │ 4  │                     │ 3  │ 4  │ 7  │ 8  │
        ├────┼────┤                     └────┴────┴────┴────┘
   b -> │ 5  │ 6  │
        ├────┼────┤
        │ 7  │ 8  │
        └────┴────┘
```

In [103]:
# Reshaping (-1 lets NumPy infer dimension automatically)
arr = np.arange(12)                               # Generates 1D array of integers from 0 to 11 (shape: (12,))
grid = arr.reshape(3, 4)
auto_grid = arr.reshape(2, -1)                    # Infer dimension -> (2, 6)

# Transposition & Flattening
transposed = grid.T                               # Swaps rows and columns (4x3)
flat_view = grid.ravel()                          # 1D memory view
flat_copy = grid.flatten()                        # 1D deep copy

# Stacking & Splitting
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
v_stacked = np.vstack((a, b))                     # Vertical stack (4, 2)
h_stacked = np.hstack((a, b))                     # Horizontal stack (2, 4)
upper, lower = np.vsplit(v_stacked, 2)            # Split back

print("Reshaped (3x4):\n", grid)
print("Transposed (4x3):\n", transposed)
print("V-Stacked:\n", v_stacked)

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed (4x3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
V-Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 6. Arithmetic & Vectorized Operations

In [104]:
# Scalar arithmetic
arr = np.array([1, 2, 3])
print("Scalar + 1:", arr + 1)
print("Scalar * 3:", arr * 3)
print("Scalar ** 2:", arr ** 2)

# Vectorized math functions (ufuncs)
# Trailing dot (.) indicates floating-point numbers (float64)
dec_arr = np.array([1.01, 2.5, 3.99])
print("Square root:", np.sqrt(dec_arr))
print("Rounded:", np.round(dec_arr))
print("Circle areas (pi * r^2):", np.pi * (arr ** 2))

# Element-wise operations between arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", a + b)
print("a * b:", a * b)
print("a / b:", a / b)

Scalar + 1: [2 3 4]
Scalar * 3: [3 6 9]
Scalar ** 2: [1 4 9]
Square root: [1.00498756 1.58113883 1.99749844]
Rounded: [1. 2. 4.]
Circle areas (pi * r^2): [ 3.14159265 12.56637061 28.27433388]
a + b: [5 7 9]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]


# 7. Broadcasting Rules

```text
Broadcasting Expansion: (1, 4) * (4, 1) ──> Output: (4, 4)

    row_vec (1, 4)          col_vec (4, 1)                Output Matrix (4, 4)
 ┌────┬────┬────┬────┐         ┌────┐                  ┌────┬────┬────┬────┐
 │ 1  │ 2  │ 3  │ 4  │         │ 1  │                  │ 1  │ 2  │ 3  │ 4  │
 └────┴────┴────┴────┘         ├────┤                  ├────┼────┼────┼────┤
        │ (Stretches           │ 2  │ (Stretches       │ 2  │ 4  │ 6  │ 8  │
        │  downwards)          ├────┤  horizontally)   ├────┼────┼────┼────┤
        ▼                      │ 3  │                  │ 3  │ 6  │ 9  │ 12 │
                               ├────┤                  ├────┼────┼────┼────┤
                               │ 4  │                  │ 4  │ 8  │ 12 │ 16 │
                               └────┘                  └────┴────┴────┴────┘
```

<p align="center">
  <img src="assets/3d_broadcasting.gif" width="480" alt="3D NumPy Broadcasting Animation">
  <br>
  <em>Figure: Visualizing 3D Broadcasting — (3, 1) and (1, 3) arrays stretching to form a (3, 3) output.</em>
</p>

In [105]:
# Broadcasting performs element-wise operations on different shapes without copying data.
# Compatibility Rule (right-to-left): Dimensions match OR one of them is 1.

# (1, 4) * (4, 1) -> Result Shape: (4, 4)
row_vec = np.array([[1, 2, 3, 4]])                # Shape: (1, 4)
col_vec = np.array([[1], [2], [3], [4]])          # Shape: (4, 1)

broadcast_table = row_vec * col_vec
print("Broadcasted Matrix:\n", broadcast_table)

# (2, 3) + (3,) -> (3,) padded to (1, 3) and stretched across rows
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print("Matrix + Row:\n", matrix + row)

Broadcasted Matrix:
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Matrix + Row:
 [[11 22 33]
 [14 25 36]]


# 8. Aggregate & Statistical Functions

```text
Understanding the Axis Parameter:
                      axis = 1  (Across Columns  ──>)
                    ┌─────────────────────────────┐
  axis = 0          │ [[ 1,  2,  3,  4,  5 ],     │  ──> Sum per row: [15, 40]
  (Down Rows  │)    │  [ 6,  7,  8,  9, 10 ]]     │
              ▼     └─────────────────────────────┘
  Sum per col:       [ 7,  9, 11, 13, 15 ]
```
<p align="center">
  <img src="assets/axis_concept.gif" width="420" alt="Axis Reduction Animation">
  <br>
  <em>Figure: Visualizing `axis=0` (column sums) vs. `axis=1` (row sums) in NumPy reductions.</em>
</p>

In [106]:
# The 'axis' parameter:
# - axis=None (default): Entire array
# - axis=0: Collapses down rows (per column)
# - axis=1: Collapses across columns (per row)

mat = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("Total Sum:", mat.sum())
print("Sum per Column (axis=0):", mat.sum(axis=0))
print("Sum per Row (axis=1):", mat.sum(axis=1))
print("Mean:", mat.mean())
print("Standard Deviation:", mat.std())
print("Variance:", mat.var())
print("Min / Max:", mat.min(), "/", mat.max())
print("Index of Max (argmax):", mat.argmax())
print("Cumulative Sum (cumsum):\n", np.cumsum(mat, axis=1))

Total Sum: 55
Sum per Column (axis=0): [ 7  9 11 13 15]
Sum per Row (axis=1): [15 40]
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Min / Max: 1 / 10
Index of Max (argmax): 9
Cumulative Sum (cumsum):
 [[ 1  3  6 10 15]
 [ 6 13 21 30 40]]


# 9. Handling Missing Data (NaNs & Infs)

In [107]:
# np.nan: Not a Number, np.inf: Infinity
data_with_nan = np.array([10.0, np.nan, 30.0, 40.0])

# Detection masks
print("Is NaN mask:", np.isnan(data_with_nan))
print("Is Finite:", np.isfinite(data_with_nan))

# Standard aggregation vs NaN-safe aggregation
print("Standard mean (returns nan):", np.mean(data_with_nan))
print("NaN-safe mean (ignores nan):", np.nanmean(data_with_nan))
print("NaN-safe sum:", np.nansum(data_with_nan))

Is NaN mask: [False  True False False]
Is Finite: [ True False  True  True]
Standard mean (returns nan): nan
NaN-safe mean (ignores nan): 26.666666666666668
NaN-safe sum: 80.0


# 10. Filtering & Boolean Indexing

```text
Boolean Filtering Pipeline:

  1. Input Array:       [  10  ,  15  ,  20  ,  25  ,  30  ,  35  ,  40  ]
                             │       │       │       │       │       │       │
  2. Condition (> 25):  [ False, False, False, False,  True,   True,  True  ] (Mask)
                                                         │       │       │
  3. Filtered Array:                                  [  30  ,  35  ,  40  ]
```

In [108]:
# Filtering (Boolean Masking) selects or modifies elements conditionally
arr = np.array([10, 15, 20, 25, 30, 35, 40])

# 1. Extraction using Boolean masks
print("Values > 25:", arr[arr > 25])
print("AND (&):", arr[(arr >= 20) & (arr <= 35)])
print("OR (|):", arr[(arr < 15) | (arr > 35)])
print("NOT (~):", arr[~(arr > 25)])

# 2. Conditional Replacement (np.where)
# Syntax: np.where(condition, value_if_true, value_if_false)
replaced = np.where(arr % 20 == 0, 999, arr)
print("np.where replaced:", replaced)

# 3. Finding Indices & Assertions
indices = np.where(arr > 25)
print("Indices where > 25:", indices[0])
print("Any > 35?", np.any(arr > 35))
print("All > 0?", np.all(arr > 0))

Values > 25: [30 35 40]
AND (&): [20 25 30 35]
OR (|): [10 40]
NOT (~): [10 15 20 25]
np.where replaced: [ 10  15 999  25  30  35 999]
Indices where > 25: [4 5 6]
Any > 35? True
All > 0? True


# 11. Sorting & Unique Values

```text
np.sort() vs. np.argsort():

  Original Array:   [  40  ,  10  ,  20  ,  30  ]
  Original Indices:     0       1       2       3

  np.sort():        [  10  ,  20  ,  30  ,  40  ]  ──> The sorted values
  np.argsort():     [   1  ,   2  ,   3  ,   0  ]  ──> The original indices in order
```

In [109]:
data = np.array([40, 10, 20, 10, 30, 40, 10])

# Sorting
sorted_copy = np.sort(data)                       # Returns a sorted copy
sort_order = np.argsort(data)                     # Returns indices that sort the array

# Unique elements & frequency counts
uniques, counts = np.unique(data, return_counts=True)

print("Sorted Array:", sorted_copy)
print("Argsort Indices:", sort_order)
print("Unique Values:", uniques)
print("Counts:", counts)

Sorted Array: [10 10 10 20 30 40 40]
Argsort Indices: [1 3 6 2 4 0 5]
Unique Values: [10 20 30 40]
Counts: [3 1 1 2]


# 12. Random Numbers & Distributions (np.random)

In [110]:
# Always use default_rng(seed) for reproducible, high-performance generation
rng = np.random.default_rng(seed=42)

# 1. Number Generation
dice_rolls = rng.integers(low=1, high=7, size=5)   # Integers in [1, 6]
uniform_floats = rng.uniform(low=10.0, high=20.0, size=3)   # 3 random floats uniformly distributed in [10.0, 20.0)
bell_curve = rng.normal(loc=0.0, scale=1.0, size=(2, 2))

# 2. Sampling (choice)
items = np.array(['Apple', 'Banana', 'Cherry', 'Date'])
chosen = rng.choice(items, size=2, replace=False)

# 3. Shuffling
deck = np.array([1, 2, 3, 4, 5])
shuffled_copy = rng.permutation(deck)             # Leaves deck unchanged
rng.shuffle(deck)                                 # Alters deck directly

print("Dice Rolls:", dice_rolls)
print("Normal (2x2):\n", bell_curve)
print("Sampled Items:", chosen)
print("In-place Shuffled Deck:", deck)

Dice Rolls: [1 5 4 3 3]
Normal (2x2):
 [[ 0.1278404  -0.31624259]
 [-0.01680116 -0.85304393]]
Sampled Items: ['Date' 'Cherry']
In-place Shuffled Deck: [2 1 4 5 3]


# 13. Linear Algebra (np.linalg)

```text
Matrix Multiplication (A @ B): (2, 2) @ (2, 2) ──> (2, 2)

      Matrix A                Matrix B                 Result Matrix
    ┌──────────┐            ┌──────────┐            ┌──────────────────┐
    │  1    2  │            │  2    0  │            │  (1*2 + 2*1)     │  ──> [ 4   4 ]
    │  3    4  │     @      │  1    2  │     =      │  (3*2 + 4*1)     │  ──> [ 10  8 ]
    └──────────┘            └──────────┘            └──────────────────┘
    (Row 0 of A)    x    (Col 0 of B)
```

In [111]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

# 1. Matrix Multiplication (@ operator or np.matmul)
mat_mul = A @ B

# 2. Determinant & Matrix Inverse
det = np.linalg.det(A)
inv_A = np.linalg.inv(A)

# 3. Vector Norm (Euclidean Distance / Magnitude)
vector_norm = np.linalg.norm(np.array([3.0, 4.0]))

# 4. Solving Systems of Linear Equations (A * x = b)
b_vec = np.array([5, 11])
solution = np.linalg.solve(A, b_vec)

print("Matrix Dot Product (A @ B):\n", mat_mul)
print("Determinant of A:", det)
print("Inverse of A:\n", inv_A)
print("Vector Norm:", vector_norm)
print("Linear System Solution (x):", solution)

Matrix Dot Product (A @ B):
 [[ 4  4]
 [10  8]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Vector Norm: 5.0
Linear System Solution (x): [1. 2.]


# 14. Saving & Loading Arrays (File I/O)

In [112]:
matrix_to_save = np.array([[1, 2, 3], [4, 5, 6]])

# 1. Fast Binary format (.npy)
np.save("reference_array.npy", matrix_to_save)
loaded_bin = np.load("reference_array.npy")

# 2. CSV / Plain Text format (.csv)
np.savetxt("reference_array.csv", matrix_to_save, delimiter=",", fmt="%d")
loaded_txt = np.loadtxt("reference_array.csv", delimiter=",")

print("Loaded Binary (.npy):\n", loaded_bin)
print("Loaded CSV (.csv):\n", loaded_txt)

Loaded Binary (.npy):
 [[1 2 3]
 [4 5 6]]
Loaded CSV (.csv):
 [[1. 2. 3.]
 [4. 5. 6.]]
